ocha_reliefweb.settings:
  type: config_object
  label: 'UNOCHA ReliefWeb integration settings.'
  mapping:
    reliefweb_api_url:
      type: string
      label: 'ReliefWeb API URL.'
    reliefweb_api_appname:
      type: string
      label: 'App name parameter to indentify the API requests.'
    reliefweb_api_cache_enabled:
      type: boolean
      label: 'Cache the API query results.'
    reliefweb_api_cache_lifetime:
      type: integer
      label: 'How long to cache the API query results.'
    reliefweb_api_cache_namespace:
      type: string
      label: 'Namespace for the cache Ids and tags.'
    reliefweb_api_verify_ssl:
      type: boolean
      label: 'Verify the SSL certificate of the API query performing requests.'
    reliefweb_website:
      type: string
      label: 'ReliefWeb site URL.'
    reliefweb_document_not_found_max_age:
      type: integer
      label: 'Max age when for a ReliefWeb document page not found response.'
    reliefweb_api_converter:
      type: string
      label: 'URL of the ReliefWeb API converter.'
    reliefweb_api_use_redirects:
      type: boolean
      label: 'Also use the "redirects" field for URL lookups.'
    reliefweb_api_post_api_schema_url:
      type: string
      label: 'Base url for the POST API JSON schemas.'
    reliefweb_api_submission_base_url:
      type: string
      label: 'Base url for the POST API submissions.'
    template_class_prefix:
      type: string
      label: 'Class prefix for the templates.'

ocha_reliefweb.reliefweb_resource_type.*:
  type: config_entity
  label: 'ReliefWeb Resource type.'
  mapping:
    settings:
      type: mapping
      label: 'Resource type settings.'
      mapping:
        disable_page_title:
          type: boolean
          label: 'Disable page title.'
        preview_warning:
          type: text_format
          label: 'Warning message when viewing the preview of an unpublished submission.'
